const FETCH_POPULAR_REQUEST = 'FETCH_POPULAR_REQUEST';
const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';

export default {
    FETCH_POPULAR_REQUEST,
    FETCH_POPULAR_SUCCESS,
    FETCH_POPULAR_FAILURE
};
